export const SET_SELECTED_FILTERS = 'SET_SELECTED_FILTERS';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SEARCH_FOR_COUNTIRES = 'SEARCH_FOR_COUNTIRES';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_NETWORK_ERROR = 'SET_NETWORK_ERROR;'